# Generated by Django 5.2.5 on 2025-08-29 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produto', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoria',
            name='slug',
            field=models.SlugField(null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='produto',
            name='slug',
            field=models.SlugField(null=True, unique=True),
        ),
    ]
